name: Django CI/CD

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main  # Run tests on pull requests to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Match your Python version1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r req.txt



  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to AWS server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.53.130.148
          cd /home/ubuntu/DemoProjectAWS
          git pull origin main
          source venv/bin/activate
          pip3 install -r req.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
          sudo systemctl reload nginx
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
